# Generated by Django 5.0.4 on 2024-04-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.vectorstock.com%2Froyalty-free-vector%2Floading-icon-in-simple-style-vector-8445211&psig=AOvVaw1zFESpVsvZJk_I7S3jaVim&ust=1714457313119000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCICY8P7g5oUDFQAAAAAdAAAAABAJ', max_length=5000),
        ),
    ]
